/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.9.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as actions_ai from "../actions/ai.js";
import type * as actions_mono from "../actions/mono.js";
import type * as actions_user from "../actions/user.js";
import type * as mutations_user from "../mutations/user.js";
import type * as templates_user from "../templates/user.js";
import type * as types_mono from "../types/mono.js";
import type * as utils from "../utils.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "actions/ai": typeof actions_ai;
  "actions/mono": typeof actions_mono;
  "actions/user": typeof actions_user;
  "mutations/user": typeof mutations_user;
  "templates/user": typeof templates_user;
  "types/mono": typeof types_mono;
  utils: typeof utils;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
